"""Heightfield pipeline: per-location LERC heightmaps + WebP/JPEG orthos.

Replaces the GLB mesh pipeline (outer/closeup/inner.glb, ~165 MB/loc) with
a 2-ring heightfield (closeup 3km/1.5m + inner 1km/0.5m, ~10-18 MB/loc).

Reads existing `tiles_v2_<slug>/manifest.json` for the location centre, then
writes outputs to `tiles_v2_<slug>/heightfield/` (LERC heightmaps + bare-
earth + 3-tier ortho in WebP+JPEG + cadastre overlay + sub-manifest).

Run:
    python3 gen_heightfield.py --slug hrensko
    python3 gen_heightfield.py --cx -624843 --cy -1095334 --out some/dir
"""
import argparse
import io
import json
import os
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional

import numpy as np
import rasterio
from rasterio.merge import merge
from scipy.ndimage import distance_transform_edt
from PIL import Image
try:
    import lerc
    HAS_LERC = True
except ImportError:
    HAS_LERC = False

Image.MAX_IMAGE_PIXELS = None

# Default LOD pyramid — overridable via --rings <json-file>. Each entry needs
# slug + half (m) + step (m) + ortho_size (px). Keep outermost ring first so
# the viewer's clipBox carve order (larger → smaller) just works.
# 3 km total area: most "regional context" use cases fit fine; the larger
# 5 km outer ring was dropped to save ~40% of total bytes per region.
# Per-ring max_z_error (m): LERC's hard upper bound on vertex Y error.
# Rule of thumb ≈ step / 7-10 — keeps quantize steps below the angular size
# of one source cell at typical viewer distance, so terracing on flat areas
# stays imperceptible. Inner ring needs tighter tolerance because the viewer
# stands inside it; closeup is mid-distance background. Per-ring values
# instead of one global default cut LERC output ~20-25% with no visible loss.
DEFAULT_RINGS = [
    {"slug": "closeup", "half": 1500, "step": 1.5, "ortho_size": 4096, "max_z_error": 0.15},
    {"slug": "inner",   "half":  500, "step": 0.5, "ortho_size": 4096, "max_z_error": 0.10},
]


def default_max_z_error_for_step(step: float) -> float:
    """Sensible LERC tolerance for a ring with given grid step (m).
    Used as fallback when a custom --rings JSON entry omits max_z_error.
    """
    return round(max(0.05, step / 7.0), 3)


def derive_rings(inner_half):
    """2-ring pyramid sized to a parcel selection (subsystem B).

    inner_half (m) is clamped to [500, 2000]; closeup = 3× inner (today's
    ratio); step = half/1000 keeps each ring a ~2000² grid so data stays
    bounded as the model grows (detail-per-metre degrades instead). At
    inner_half=500 the geometry equals DEFAULT_RINGS.
    """
    inner_half = max(500.0, min(2000.0, float(inner_half)))
    closeup_half = 3.0 * inner_half
    inner_step = inner_half / 1000.0
    closeup_step = closeup_half / 1000.0
    return [
        {"slug": "closeup", "half": closeup_half, "step": closeup_step,
         "ortho_size": 4096, "max_z_error": default_max_z_error_for_step(closeup_step)},
        {"slug": "inner", "half": inner_half, "step": inner_step,
         "ortho_size": 4096, "max_z_error": default_max_z_error_for_step(inner_step)},
    ]


def resolve_rings(rings_file, inner_half):
    """Pick the ring list: explicit --rings file wins (loaded + validated),
    then --inner-half (selection-driven), else fixed DEFAULT_RINGS (legacy)."""
    if rings_file:
        rings = json.loads(Path(rings_file).read_text())
        for r in rings:
            for k in ("slug", "half", "step", "ortho_size"):
                if k not in r:
                    raise SystemExit(f"--rings entry missing '{k}': {r}")
            # max_z_error optional in custom JSON; derive from step otherwise.
            if "max_z_error" not in r:
                r["max_z_error"] = default_max_z_error_for_step(r["step"])
        return rings
    if inner_half is not None:
        return derive_rings(inner_half)
    return DEFAULT_RINGS


# Ortho quality tiers — gen emits one JPEG per tier per ring so the viewer
# can switch quality at runtime. `ortho_size` on a ring sets the HIGH-tier
# resolution; low/mid are halved/quartered. Subsampling 0 = 4:4:4 (no chroma
# downsample, best quality, larger), 2 = 4:2:0 (standard photo JPEG, ~25%
# smaller, no visible quality drop on aerial imagery).
ORTHO_TIERS = {
    "low":   {"scale": 0.25, "quality": 75, "subsampling": 2, "webp_quality": 70},
    "mid":   {"scale": 0.50, "quality": 80, "subsampling": 2, "webp_quality": 75},
    "high":  {"scale": 1.00, "quality": 92, "subsampling": 0, "webp_quality": 88},
    # ultra: 2× composite. For closeup (3 km extent, ortho_size=4096) the
    # composite jumps to 8192² ≈ 0.37 m/px — ČÚZK SM5 ortho source is at
    # ~0.125 m/px so we're still well below source resolution. Worth it
    # only for high-detail screenshots; KTX2 ETC1S file roughly 4× the
    # high-tier .ktx2. Not generated by default (memory-intensive).
    "ultra": {"scale": 2.00, "quality": 95, "subsampling": 0, "webp_quality": 92},
    # super: 4× composite (closeup 16384² ≈ 0.18 m/px — closest to ČÚZK
    # SM5 source 0.125 m/px). KTX2 ~32 MB on disk, ~128 MB GPU per ring.
    # Desktop GL hits the MAX_TEXTURE_SIZE=16384 ceiling on most cards;
    # iPad/mobile typically cap at 8192². Generate only when chasing a
    # hero screenshot; viewer dispose-tier logic keeps it from staying
    # resident if user switches away.
    "super": {"scale": 4.00, "quality": 95, "subsampling": 0, "webp_quality": 92},
}


def resolve_cache_dir(cli_path: Optional[str]) -> Path:
    """CLI > env > default sibling project. An explicit CLI/env path that
    doesn't exist is a hard error (user typo'd); only the default fallback
    is allowed to be missing."""
    if cli_path:
        p = Path(cli_path)
        if not p.is_dir():
            raise SystemExit(f"--cache-dir {cli_path!r} not a directory")
        return p
    env = os.environ.get("INZERATOR_CACHE")
    if env:
        p = Path(env)
        if not p.is_dir():
            raise SystemExit(f"INZERATOR_CACHE={env!r} not a directory")
        return p
    default = Path("/Users/jan/projekty/inzerator/cache")
    if default.is_dir():
        return default
    raise SystemExit(
        "No inzerator cache found. Pass --cache-dir <path>, set "
        "INZERATOR_CACHE env var, or run from a sibling of inzerator/."
    )


CACHE_DIR: Optional[Path] = None   # populated in main() from CLI/env


def discover_sm5(cx, cy, half):
    out = []
    for d in sorted(CACHE_DIR.glob("dmpok_tiff_*")):
        for tif in d.glob("*.tif"):
            with rasterio.open(tif) as src:
                b = src.bounds
                if not (cx + half < b.left or cx - half > b.right
                        or cy + half < b.bottom or cy - half > b.top):
                    out.append(str(tif))
    return out


def ensure_sm5_cached(cx, cy, half, *, fetch_missing=True):
    """Resolve every SM5 sheet whose bbox intersects (cx±half, cy±half) and
    make sure the cache directory `CACHE_DIR/ortofoto_<MAPNOM>/` has a
    JPG+JGW pair for each. Missing tiles are downloaded via
    `download_ortofoto.download(code, CACHE_DIR)`.

    `fetch_missing=False` makes this read-only — we only print which
    sheets are missing and let `discover_ortho` produce a composite with
    holes. Use that for diagnostics or when the network is unavailable.

    Returns a list of MAPNOM codes that were downloaded this call (empty
    if everything was already cached or fetch_missing=False).
    """
    import urllib.parse, urllib.request, json
    bbox = (cx - half, cy - half, cx + half, cy + half)
    url = "https://ags.cuzk.cz/arcgis/rest/services/KladyMapovychListu/MapServer/24/query"
    params = {
        "geometry": json.dumps({
            "xmin": bbox[0], "ymin": bbox[1], "xmax": bbox[2], "ymax": bbox[3],
            "spatialReference": {"wkid": 5514},
        }),
        "geometryType": "esriGeometryEnvelope",
        "spatialRel": "esriSpatialRelIntersects",
        "outFields": "MAPNOM", "f": "json", "returnGeometry": "false",
    }
    req = urllib.request.Request(
        f"{url}?{urllib.parse.urlencode(params)}",
        headers={"User-Agent": "Mozilla/5.0"},
    )
    try:
        data = json.loads(urllib.request.urlopen(req, timeout=30).read())
    except Exception as e:
        print(f"  ⚠ SM5 grid lookup failed ({e}); using whatever's cached")
        return []
    codes = sorted({f["attributes"]["MAPNOM"] for f in data.get("features", [])})

    def _is_cached(code):
        d = CACHE_DIR / f"ortofoto_{code}"
        if not d.is_dir():
            return False
        # JPG + matching JGW is what discover_ortho actually needs.
        for jpg in d.glob("*.jpg"):
            if jpg.with_suffix(".jgw").exists():
                return True
        return False

    missing = [c for c in codes if not _is_cached(c)]
    if not missing:
        return []
    print(f"  SM5 cache: {len(codes)} sheets in bbox, {len(missing)} missing: {missing}")
    if not fetch_missing:
        print(f"  (fetch_missing=False — composite will have empty stripes)")
        return []
    downloaded = []
    import download_ortofoto as _dl
    for code in missing:
        try:
            print(f"  fetching SM5 sheet {code}…")
            _dl.download(code, CACHE_DIR, force=False)
            downloaded.append(code)
        except SystemExit as e:
            # download_ortofoto uses SystemExit on hard failures (no
            # ATOM feed entry, no .zip URL). Log and continue so the
            # other sheets still get fetched.
            print(f"  ⚠ SM5 {code} download failed: {e}")
        except Exception as e:
            print(f"  ⚠ SM5 {code} download error: {e}")
    return downloaded


def discover_ortho(cx, cy, half):
    out = []
    for d in sorted(CACHE_DIR.glob("ortofoto_*")):
        for jgw in d.glob("*.jgw"):
            if "TM3" in jgw.name:
                continue
            text = jgw.read_text().splitlines()
            px_x = float(text[0])
            py_y = float(text[3])
            x0 = float(text[4])
            y0 = float(text[5])
            jpg = jgw.with_suffix(".jpg")
            if not jpg.exists():
                continue
            with Image.open(jpg) as im:
                w, h = im.size
            left, right = x0, x0 + w * px_x
            top, bottom = y0, y0 + h * py_y
            lo_x, hi_x = min(left, right), max(left, right)
            lo_y, hi_y = min(top, bottom), max(top, bottom)
            if not (hi_x <= cx - half or lo_x >= cx + half
                    or hi_y <= cy - half or lo_y >= cy + half):
                out.append((jpg, px_x, py_y, x0, y0, w, h))
    return out


DMR5G_URL = (
    "https://ags.cuzk.gov.cz/arcgis/rest/services/3D/dmr5g/ImageServer/exportImage"
)
# Cadastre raster comes from the inzerator dev server's proxy, which already
# handles ČÚZK WMS quirks (axis order, retry on Errno 61, alpha-cutting white
# background). Pre-fetching once at gen time means the viewer never depends
# on the inzerator server being up.
INZERATOR_PROXY = os.environ.get("INZERATOR_PROXY", "http://127.0.0.1:8080")


def fetch_dmr5g(cx, cy, half, step):
    """Fetch a single ČÚZK DMR5G bare-earth GeoTIFF for the given bbox.

    DMR5G is the ground-only LIDAR product — no buildings, no vegetation.
    Returns a rasterio dataset opened from in-memory bytes.

    Retry policy: ČÚZK ArcGIS occasionally rate-limits (Errno 61 Connection
    refused) for several minutes at a time. Aggressive backoff isn't enough;
    we need real patience. 8 attempts × cumulative ~8 min wall-clock — first
    few are fast (transient blip), later attempts wait minutes (rate-limit
    cooldown). Print each retry so the caller knows we're not hung.
    """
    n = int(round(2 * half / step)) + 1
    n = max(50, min(2048, n))
    bbox = f"{cx-half},{cy-half},{cx+half},{cy+half}"
    url = (
        f"{DMR5G_URL}?bbox={bbox}&bboxSR=5514&imageSR=5514"
        f"&size={n},{n}&format=tiff&pixelType=F32&f=image"
    )
    waits = [2, 5, 10, 20, 40, 90, 180]    # 7 waits between 8 attempts
    last_err = None
    for attempt, wait in enumerate([0] + waits):
        if wait > 0:
            print(f"    DMR5G retry {attempt}/8 after {wait}s "
                  f"(last error: {last_err})")
            time.sleep(wait)
        try:
            with urllib.request.urlopen(url, timeout=120) as r:
                return io.BytesIO(r.read())
        except (urllib.error.URLError, ConnectionError, TimeoutError, OSError) as e:
            last_err = e
    raise SystemExit(
        f"DMR5G fetch failed after 8 attempts (~8 min wall-clock): {last_err}\n"
        f"ČÚZK ArcGIS is unreachable. Try again later or check "
        f"https://ags.cuzk.gov.cz/arcgis/rest/services/3D/dmr5g/ImageServer"
    )


def _encode_lerc(data, out_path, max_z_error=0.10):
    """Encode (H, W) Float32 array as LERC binary file (Esri's raster codec).

    `max_z_error` (m): hard upper bound on per-cell elevation error in the
    decoded output. 0 = lossless (often LARGER than PNG for our data).
    0.10 = 10 cm tolerance, comfortably below ČÚZK DMPOK's 10-30 cm RMS
    source error — i.e. "lossless vs source" but ~50% of PNG size.

    Browser decode via WASM `lerc` npm package: returns Float32Array
    with absolute elevation values in metres (no decoding maths).
    """
    if not HAS_LERC:
        raise SystemExit(
            "lerc Python package not installed. Run: pip3 install --user lerc"
        )
    arr = np.ascontiguousarray(data.astype(np.float32))
    hint = arr.nbytes + 1024
    code, nbytes, buf = lerc.encode(arr, 1, False, None, max_z_error, hint)
    if code != 0:
        raise SystemExit(f"LERC encode failed with code {code}")
    out_path.write_bytes(bytes(buf[:nbytes]))


def _encode_heightmap(data, y_min, y_max, out_path, bits=16):
    """Encode a (H, W) float array as RG-channel PNG over `bits` precision.

    Layout per pixel:
      16-bit: R = top 8 bits, G = bottom 8 bits        (full byte each)
      12-bit: R = top 8 bits, G = bottom 4 bits in TOP nibble of byte
      10-bit: R = top 8 bits, G = bottom 2 bits in TOP 2 bits of byte
       8-bit: R = all 8 bits, G = 0
    G's unused low bits stay zero so PNG zlib compresses them away.
    """
    max_val = (1 << bits) - 1
    norm = ((data - y_min) / max(y_max - y_min, 1e-6) * max_val)
    norm = np.clip(norm, 0, max_val).astype(np.uint32)
    if bits == 16:
        hi = (norm >> 8).astype(np.uint8)
        lo = (norm & 0xFF).astype(np.uint8)
    elif bits == 12:
        hi = (norm >> 4).astype(np.uint8)             # top 8 of 12 → R
        lo = ((norm & 0x0F) << 4).astype(np.uint8)    # low 4 in high nibble of G
    elif bits == 10:
        hi = (norm >> 2).astype(np.uint8)             # top 8 of 10 → R
        lo = ((norm & 0x03) << 6).astype(np.uint8)    # low 2 in top 2 bits of G
    elif bits == 8:
        hi = norm.astype(np.uint8)                    # all 8 → R
        lo = np.zeros_like(hi)
    else:
        raise SystemExit(f"unsupported bits: {bits}")
    rgb = np.stack([hi, lo, np.zeros_like(hi)], axis=-1)
    Image.fromarray(rgb, "RGB").save(out_path, optimize=True, compress_level=9)


def _fetch_sm5_grid(cx, cy, half, step):
    """Merge SM5 sheets into a single (rows, cols) array. Nodata holes filled
    via nearest-valid (EDT). Returns the array; caller despikes + encodes."""
    sm5_paths = discover_sm5(cx, cy, half)
    if not sm5_paths:
        raise SystemExit(f"No SM5 cache covers ({cx}, {cy}) half={half}.")
    srcs = [rasterio.open(p) for p in sm5_paths]
    try:
        merged, _ = merge(
            srcs,
            bounds=(cx - half, cy - half, cx + half, cy + half),
            res=(step, step),
            nodata=-9999.0,
        )
    finally:
        for s in srcs:
            s.close()
    data = merged[0]
    bad = (data <= 0) | (data == -9999.0)
    if bad.any():
        if (~bad).any():
            _, (rr, cc) = distance_transform_edt(bad, return_indices=True)
            data = data[rr, cc]
        else:
            data[:] = 0
    return data


def despike_sm5(sm5_data, bare_data, dmr_ceiling=50.0):
    """Port of gen_detail.py despike — removes SM5 anomalies that would
    otherwise show as 50-400 m vertical spikes in the heightfield.

    Two-stage cleanup:
      (A) Morphology-based — 8-neighbour outlier detection:
          • isolated upward spike (cell >5 m above ALL 8 neighbours)
          • downward pit (cell >3 m below ALL 8 neighbours)
          • cluster anomalies inside dilated pit zones (|Δmedian|>3 m)
      (B) DMR5G-based — physical impossibility filter:
          • cells >ceiling above bare-earth → reduced toward bare+ceiling
          • cells >ceiling below bare-earth → replaced with bare
            (Hřensko-mega cluster glitch produced -385 m pits — below
            ground is physically impossible since LIDAR can't see there).

    bare_data must already be at the same grid shape as sm5_data.
    """
    from scipy.ndimage import (
        median_filter, minimum_filter, maximum_filter, binary_dilation,
    )
    sm5_float = sm5_data.astype("float64")

    footprint = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 1]])
    nb_min = minimum_filter(sm5_float, footprint=footprint, mode="nearest")
    nb_max = maximum_filter(sm5_float, footprint=footprint, mode="nearest")

    isolated_up = sm5_float > (nb_max + 5.0)
    pit = sm5_float < (nb_min - 3.0)
    anomaly_zone = binary_dilation(pit, iterations=6)
    med = median_filter(sm5_float, size=3)
    delta = sm5_float - med
    cluster_in_zone = anomaly_zone & (np.abs(delta) > 3.0)

    needs_fix = isolated_up | pit | cluster_in_zone
    n_morph = int(needs_fix.sum())
    sm5_float = np.where(needs_fix, med, sm5_float)

    n_ceil = n_floor = 0
    if bare_data is not None and dmr_ceiling > 0:
        bare = bare_data.astype("float64")
        above = sm5_float > (bare + dmr_ceiling)
        if above.any():
            med2 = median_filter(sm5_float, size=3)
            replacement = np.where(med2 <= bare + dmr_ceiling, med2, bare)
            sm5_float = np.where(above, replacement, sm5_float)
            n_ceil = int(above.sum())
        below = sm5_float < (bare - dmr_ceiling)
        if below.any():
            sm5_float = np.where(below, bare, sm5_float)
            n_floor = int(below.sum())

    if n_morph or n_ceil or n_floor:
        print(f"  despike: {n_morph} morph spikes, "
              f"{n_ceil} above-bare, {n_floor} below-bare cells fixed")
    return sm5_float.astype(sm5_data.dtype)


def _encode_heightmap_file(data, y_min, y_max, out_path, max_z_error=0.10):
    """Dispatch encoder by file extension. `max_z_error` is the LERC tolerance
    in metres (ignored for PNG path, which uses fixed 16-bit precision)."""
    if str(out_path).endswith('.lerc'):
        _encode_lerc(data, out_path, max_z_error)
    else:
        _encode_heightmap(data, y_min, y_max, out_path)


def fetch_cadastre(cx, cy, half, size, out_path):
    """Fetch a SJTSK-aligned cadastre overlay PNG (boundaries + parcel numbers
    + buildings outline) from the inzerator proxy. Transparent background.

    PNG is alpha-cut on the proxy side: lines + numbers are opaque, white
    space is transparent. Viewer overlays via `mix(orto, cad.rgb, cad.a)`.
    """
    bbox = f"{cx-half},{cy-half},{cx+half},{cy+half}"
    url = f"{INZERATOR_PROXY}/proxy/cadastre?BBOX={bbox}&layer=KN&size={size}"
    last_err = None
    for attempt in range(3):
        try:
            with urllib.request.urlopen(url, timeout=180) as r:
                out_path.write_bytes(r.read())
            return True
        except (urllib.error.URLError, ConnectionError, TimeoutError, OSError) as e:
            last_err = e
            if attempt < 2:
                time.sleep(1 + attempt * 2)
    print(f"  ⚠ cadastre fetch failed: {last_err}")
    return False


def fetch_vector_cadastre(cx, cy, half, parcels_path, buildings_path):
    """Fetch RÚIAN parcel + building polygons via the inzerator server's
    /api/parcels and /api/buildings endpoints, save as JSON next to the
    raster cadastre. The vector path lets the viewer drop the 64 MB R8
    cadastre raster (per ring) for ~1 MB of vector lines — 50× GPU saving.

    Parcels come with per-vertex DSM-sampled Y; buildings are 2D only
    (viewer drapes them via the ring's heightmap at load time). Both use
    a local frame relative to (cx, cy): lx = sx - cx, lz = -(sy - cy).

    /api/parcels has its own retry+backoff on the server side, so we
    only retry on transport failures.
    """
    base = INZERATOR_PROXY.rstrip("/")
    # Server clamps radius to 2000 m, which covers our largest ring (1500 m).
    radius = min(2000.0, float(half))
    urls = {
        "parcels":   f"{base}/api/parcels?gcx={cx}&gcy={cy}&radius={radius}",
        "buildings": f"{base}/api/buildings?gcx={cx}&gcy={cy}&radius={radius}",
    }
    out_paths = {"parcels": parcels_path, "buildings": buildings_path}
    counts = {}
    for kind, url in urls.items():
        last_err = None
        ok = False
        for attempt in range(3):
            try:
                with urllib.request.urlopen(url, timeout=180) as r:
                    body = r.read()
                # Parse to sanity-check + count features for the log.
                data = json.loads(body)
                out_paths[kind].write_bytes(body)
                counts[kind] = len(data)
                ok = True
                break
            except (urllib.error.URLError, ConnectionError,
                    TimeoutError, OSError, ValueError) as e:
                last_err = e
                if attempt < 2:
                    time.sleep(1 + attempt * 2)
        if not ok:
            print(f"  ⚠ vector {kind} fetch failed: {last_err}")
            return None
    return counts


def decode_bare_from_disk(path):
    """Read an existing bare LERC/PNG into a Float64 array.

    Used when the cached bare file exists on disk (from a previous run) and
    we want to skip the ČÚZK live fetch — DMR5G is stable, so reusing the
    on-disk encode is safe and resilient against ArcGIS outages.
    """
    if str(path).endswith('.lerc'):
        if not HAS_LERC:
            raise SystemExit("LERC decode requested but lerc package missing.")
        buf = path.read_bytes()
        # lerc.decode returns (code, array, mask). code != 0 = decode failure.
        code, arr, _mask = lerc.decode(buf)
        if code != 0:
            raise SystemExit(f"LERC decode failed for {path} (code {code})")
        return arr.astype(np.float64)
    # PNG fallback (RG-channel encoded) — caller is responsible for y_min/y_max.
    raise SystemExit(f"PNG bare decode not implemented for {path}")


def fetch_bare_grid(cx, cy, half, step):
    """Fetch DMR5G bare-earth, fill nodata, resize to the SM5 grid shape.
    Returns the array; caller chooses when to encode it (we need it twice:
    as despike reference and as the output `<slug>_bare.lerc`)."""
    tif_bytes = fetch_dmr5g(cx, cy, half, step)
    with rasterio.open(tif_bytes) as src:
        bare = src.read(1).astype(np.float64)
    bad = (bare <= 0) | (bare == -9999.0) | ~np.isfinite(bare)
    if bad.any() and (~bad).any():
        _, (rr, cc) = distance_transform_edt(bad, return_indices=True)
        bare = bare[rr, cc]
    # ČÚZK's ImageServer can return a slightly different size than requested
    # (off-by-one rounding). Resize to the requested grid so shader UVs line up.
    n = int(round(2 * half / step)) + 1
    n = max(50, min(2048, n))
    if bare.shape != (n, n):
        bare = np.array(
            Image.fromarray(bare).resize((n, n), Image.BILINEAR),
            dtype=np.float64,
        )
    return bare


def build_ortho_composite(cx, cy, half, out_size):
    """Composite SM5 ortho sheets onto an SJTSK-aligned `out_size` canvas.

    Returns the in-memory PIL Image; caller chooses output format(s) so we
    encode once per format from a single shared composite.
    """
    sheets = discover_ortho(cx, cy, half)
    if not sheets:
        raise SystemExit(f"No ortho cache covers ({cx}, {cy}) half={half}.")
    bbox = (cx - half, cy - half, cx + half, cy + half)
    px_per_m = out_size / (2 * half)
    composite = Image.new("RGB", (out_size, out_size), (0, 0, 0))
    for jpg, px_x, py_y, x0, y0, w, h in sheets:
        s_left, s_right = x0, x0 + w * px_x
        s_top, s_bottom = y0, y0 + h * py_y
        s_lo_x, s_hi_x = min(s_left, s_right), max(s_left, s_right)
        s_lo_y, s_hi_y = min(s_top, s_bottom), max(s_top, s_bottom)
        ox_lo = max(s_lo_x, bbox[0]); ox_hi = min(s_hi_x, bbox[2])
        oy_lo = max(s_lo_y, bbox[1]); oy_hi = min(s_hi_y, bbox[3])
        if ox_hi <= ox_lo or oy_hi <= oy_lo:
            continue
        sa_x = (ox_lo - x0) / px_x
        sb_x = (ox_hi - x0) / px_x
        sa_y = (oy_hi - y0) / py_y
        sb_y = (oy_lo - y0) / py_y
        spl = max(0, int(round(min(sa_x, sb_x))))
        spr = min(w, int(round(max(sa_x, sb_x))))
        spt = max(0, int(round(min(sa_y, sb_y))))
        spb = min(h, int(round(max(sa_y, sb_y))))
        if spr <= spl or spb <= spt:
            continue
        with Image.open(jpg) as src_img:
            crop = src_img.crop((spl, spt, spr, spb))
        dst_w = int(round((ox_hi - ox_lo) * px_per_m))
        dst_h = int(round((oy_hi - oy_lo) * px_per_m))
        crop = crop.resize((dst_w, dst_h), Image.LANCZOS)
        dpl = int(round((ox_lo - bbox[0]) * px_per_m))
        dpt = int(round((bbox[3] - oy_hi) * px_per_m))
        composite.paste(crop, (dpl, dpt))
    return composite


def write_json_atomic(path, payload):
    """Write JSON to `path` via tmp+rename so an interrupted run can't leave a
    half-written manifest. Critical for refresh runs that span many minutes —
    losing the manifest means losing the only record of which files belong
    to a ring (`ortho_tiers`, `ortho_size`, etc.)."""
    path = Path(path)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2))
    os.replace(tmp, path)


def encode_cadastre_ktx2(src_png, out_ktx2):
    """Encode a cadastre alpha PNG to KTX2 (ETC1S) via basisu.

    Pipeline: PNG RGBA → extract alpha → downsample to 4096² → save as
    grayscale JPG (basisu chokes on PNG-with-alpha as a single-channel
    source — it reads alpha as a second slice and refuses single-output
    mode). Encode JPG → KTX2 ETC1S.

    GPU footprint: 4096² × 0.5 byte/pixel (ETC1S transcoded to BC1/EAC)
    = 8 MB per ring vs. 64 MB for the raw 8192² R8 path = 8× saving.
    Disk: ~0.8 MB per ring vs. ~1-2 MB for the PNG.
    """
    import tempfile
    with Image.open(src_png) as pim:
        if pim.mode == "RGBA":
            arr = np.array(pim)[..., 3]   # alpha channel
        elif pim.mode == "LA":
            arr = np.array(pim)[..., 1]
        else:
            arr = np.array(pim.convert("L"))
        # Downsample to 4096² via LANCZOS — keeps thin lines crisp better
        # than nearest-neighbour at 2× shrink ratio. Cadastre PNG is square
        # by construction (SJTSK-aligned).
        gray = Image.fromarray(arr).resize((4096, 4096), Image.LANCZOS)
    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tf:
        tmp_jpg = tf.name
    try:
        # quality=95 is well above ETC1S re-quantisation noise floor — bumping
        # higher just inflates the temp JPG without affecting KTX2 output.
        gray.save(tmp_jpg, quality=95)
        subprocess.run([
            "basisu", "-ktx2", "-q", "220", "-comp_level", "4",
            tmp_jpg, "-output_file", str(out_ktx2),
        ], check=True, capture_output=True, text=True)
    finally:
        try: os.unlink(tmp_jpg)
        except OSError: pass


def encode_ortho_ktx2(src_path, out_path):
    """Encode an ortho image to KTX2 (ETC1S) via the basisu CLI.

    ETC1S transcodes on the client to BC1 (desktop) / ETC2 (mobile) /
    ASTC — all 0.5–1 byte per pixel on the GPU vs. 3–4 bytes for raw
    RGB/RGBA. 4096² ortho_high drops from ~50 MB to ~8 MB of VRAM, and
    the .ktx2 on disk is ~2 MB vs. ~6 MB JPG. Quality is marginally
    softer than JPG q=92 but on terrain at typical viewer distances
    the difference is invisible.

    `basisu` is a build-time tool (Homebrew `basis-universal`); the
    viewer never invokes it. If missing, raises FileNotFoundError and
    the caller silently skips KTX2 generation — JPG/WebP fallbacks
    keep the manifest usable.
    """
    # No -y_flip: KTX2 stores in image-native order; the shader compensates
    # via uOrthoFlipY because compressed textures can't be flipped at upload
    # (WebGL ignores UNPACK_FLIP_Y_WEBGL for compressed paths).
    # -q 220 (default 128, max 255): pushes ETC1S quality up — file ~2×
    # vs. q=128 but ETC1S block artifacts on grass / rooftop edges become
    # much less visible. -comp_level 2 (default 1, max 6): comp_level 4 was
    # measured at 113 s for an 8192² ultra tile — the dominant cost of the
    # whole heightfield gen. Level 2 roughly halves that for a difference
    # invisible on terrain at viewer distance; level 1 is faster still if
    # gen time matters more than the last few % of block fit.
    subprocess.run([
        "basisu", "-ktx2", "-q", "220", "-comp_level", "2",
        str(src_path), "-output_file", str(out_path),
    ], check=True, capture_output=True, text=True)


def save_ortho_jpeg(composite, out_path, quality, subsampling):
    # progressive=True: same byte count, but renders top-down low-res first,
    # so the viewer shows something useful at ~30% of bytes received.
    composite.save(out_path, quality=quality, optimize=True,
                   subsampling=subsampling, progressive=True)


TILES_DIR_PREFIX = "tiles_v2_"


def resolve_slug_paths(slug, cli_cx=None, cli_cy=None):
    """Resolve (cx, cy, out_dir) for a slug. Out dir is
    `tiles_v2_<slug>/heightfield/`.

    Centre lookup order (after v2 viewer was retired in 2026-06):
      1. CLI --cx/--cy if both provided — primary path for new locations
         driven by locations.py (which knows cx/cy from the job spec).
      2. Existing heightfield sub-manifest at heightfield/manifest.json —
         the path for re-generating an existing heightfield without
         passing coords again.
      3. Legacy v2 top-level manifest at tiles_v2_<slug>/manifest.json —
         pre-v2-retirement lokace whose top-manifest hasn't been moved
         to TOBEDELETED/ yet. Allows `gen_heightfield.py --slug X` on
         legacy locations without breakage.

    If none of the three sources have coords, SystemExit.
    """
    loc_dir = Path(f"{TILES_DIR_PREFIX}{slug}")
    out_dir = loc_dir / "heightfield"

    # Path 1: explicit CLI coords. Most authoritative; no disk read.
    if cli_cx is not None and cli_cy is not None:
        return float(cli_cx), float(cli_cy), out_dir

    if not loc_dir.is_dir():
        raise SystemExit(
            f"--slug {slug!r}: directory {loc_dir} not found and no "
            f"--cx/--cy provided")

    # Path 2: heightfield sub-manifest (re-gen case).
    hf_manifest = out_dir / "manifest.json"
    if hf_manifest.is_file():
        m = json.loads(hf_manifest.read_text())
        cx, cy = m.get("cx"), m.get("cy")
        if cx is not None and cy is not None:
            return float(cx), float(cy), out_dir

    # Path 3: legacy v2 top-level manifest.
    legacy = loc_dir / "manifest.json"
    if legacy.is_file():
        m = json.loads(legacy.read_text())
        details = m.get("details") or []
        if details and "center_sjtsk" in details[0]:
            cx, cy = details[0]["center_sjtsk"]
            return float(cx), float(cy), out_dir

    raise SystemExit(
        f"--slug {slug!r}: no centre found. Pass --cx and --cy, or run "
        f"after the heightfield step has produced "
        f"{hf_manifest}, or have the legacy v2 manifest at {legacy}.")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--slug", default=None,
                   help="location slug. Writes to tiles_v2_<slug>/heightfield/. "
                        "Centre resolved from --cx/--cy if both given; "
                        "otherwise from heightfield/manifest.json (re-gen) "
                        "or the legacy v2 top-level manifest.json. "
                        "Overrides --out.")
    p.add_argument("--cx", type=float, default=None,
                   help="S-JTSK X centre. Required unless --slug points to "
                        "an existing location with a heightfield or legacy "
                        "v2 manifest from which centre can be recovered.")
    p.add_argument("--cy", type=float, default=None,
                   help="S-JTSK Y centre. See --cx.")
    p.add_argument("--out", default=".",
                   help="output directory (default = cwd)")
    p.add_argument("--cache-dir", default=None,
                   help="inzerator cache root with dmpok_tiff_* / ortofoto_* "
                        "(env: INZERATOR_CACHE; default: "
                        "/Users/jan/projekty/inzerator/cache)")
    p.add_argument("--rings", default=None,
                   help="JSON file with [{slug, half, step, ortho_size}, …] "
                        "(default: 5km/3km/1km outer/closeup/inner preset)")
    p.add_argument("--inner-half", type=float, default=None,
                   help="inner-ring half-extent in m (selection-driven gen). "
                        "Builds a 2-ring pyramid via derive_rings (clamped "
                        "500–2000). Ignored if --rings is given. Default: "
                        "DEFAULT_RINGS fixed preset.")
    p.add_argument("--no-cadastre", action="store_true",
                   help="skip cadastre fetch (saves ~500 KB/ring, but viewer "
                        "won't have parcel boundaries unless it fetches live)")
    # Bare-earth caching is auto-on: if `<slug>_bare.lerc` exists on disk we
    # skip the live DMR5G fetch and decode the cached file. Use --refresh-bare
    # to force a refetch (e.g. when ČÚZK has republished SM5G).
    p.add_argument("--refresh-bare", action="store_true",
                   help="force live DMR5G refetch even if cached bare exists.")
    p.add_argument("--no-fetch-missing", action="store_true",
                   help="don't auto-download missing SM5 ortofoto sheets; "
                        "the composite will have empty stripes where cache "
                        "is missing. Default: auto-fetch via ČÚZK ATOM feed.")
    p.add_argument("--cadastre-size", type=int, default=8192,
                   help="cadastre PNG side in px (default 8192; server caps at 8192)")
    p.add_argument("--bits", type=int, default=16, choices=[8, 10, 12, 16],
                   help="(PNG only) heightmap bit depth: 16=full, 12=source-tier "
                        "(3cm), 10=14cm steps, 8=50cm steps")
    p.add_argument("--format", default="lerc", choices=["png", "lerc"],
                   help="heightmap format: lerc (default, WASM-decoded, "
                        "-50%% vs PNG) or png (legacy fallback).")
    p.add_argument("--max-z-error", type=float, default=None,
                   help="(LERC only) GLOBAL override for max vertical error "
                        "in metres across all rings. By default each ring "
                        "uses its own value (closeup=0.15, inner=0.10). "
                        "Set this to force a single tolerance, e.g. 0.05 "
                        "for archival-grade or 0.30 for size-minimised.")
    p.add_argument("--ortho-tiers", default="mid,high,ultra",
                   help="comma-separated list of ortho quality tiers to emit. "
                        "low=1024², mid=2048², high=4096², ultra=8192², "
                        "super=16384² (closest to ČÚZK source). Viewer can "
                        "switch live. Default: mid,high,ultra (mid doubles "
                        "as the viewer's fast boot tier; no super — opt-in "
                        "via refresh_ortho.py).")
    p.add_argument("--ortho-default", default="ultra",
                   choices=["low", "mid", "high", "ultra", "super"],
                   help="the tier the viewer settles on (it boots on `mid` "
                        "and upgrades to this in the background) and the "
                        "target of the manifest's legacy `ortho_file` alias. "
                        "Must be one of the tiers in --ortho-tiers. Default: "
                        "ultra (since 2026-05-25; KTX2 ETC1S makes the 32 MB "
                        "GPU cost acceptable on most devices).")
    args = p.parse_args()
    if args.slug:
        cx, cy, out_dir = resolve_slug_paths(args.slug, args.cx, args.cy)
        args.cx, args.cy = cx, cy
        args.out = str(out_dir)
        print(f"Slug {args.slug!r}: centre=({cx:.2f}, {cy:.2f}) "
              f"→ {out_dir}/")
    elif args.cx is None or args.cy is None:
        raise SystemExit("Need --slug, or --cx + --cy + --out.")
    tiers = [t.strip() for t in args.ortho_tiers.split(",") if t.strip()]
    for t in tiers:
        if t not in ORTHO_TIERS:
            raise SystemExit(f"Unknown ortho tier: {t!r}. Valid: {list(ORTHO_TIERS)}")
    if args.ortho_default not in tiers:
        raise SystemExit(
            f"--ortho-default {args.ortho_default!r} not in --ortho-tiers {tiers}")

    # CACHE_DIR is a module-level singleton read by discover_sm5/discover_ortho.
    global CACHE_DIR
    CACHE_DIR = resolve_cache_dir(args.cache_dir)
    print(f"Using cache: {CACHE_DIR}")
    if args.format == 'lerc':
        if not HAS_LERC:
            raise SystemExit("--format lerc requested but lerc package missing. "
                             "Run: pip3 install --user lerc")
        if args.max_z_error is not None:
            print(f"LERC mode, max z-error: {args.max_z_error} m (global override)")
        else:
            print(f"LERC mode, per-ring max z-error")

    rings = resolve_rings(args.rings, args.inner_half)
    if args.rings:
        print(f"Using custom rings from {args.rings}: "
              f"{[r['slug'] for r in rings]}")
    elif args.inner_half is not None:
        print(f"Using selection-driven rings (inner_half={args.inner_half}): "
              f"inner half={rings[1]['half']} step={rings[1]['step']}, "
              f"closeup half={rings[0]['half']} step={rings[0]['step']}")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest = {"cx": args.cx, "cy": args.cy, "rings": []}

    total_bytes = 0
    for ring in rings:
        slug = ring["slug"]
        half = ring["half"]
        step = ring["step"]
        size = ring["ortho_size"]
        # CLI override wins over per-ring value; per-ring wins over derived.
        if args.max_z_error is not None:
            ring_mze = args.max_z_error
        elif "max_z_error" in ring:
            ring_mze = ring["max_z_error"]
        else:
            ring_mze = default_max_z_error_for_step(step)
        print(f"\n=== Ring '{slug}': {2*half}×{2*half} m, step {step} m, "
              f"ortho {size}², LERC ±{ring_mze} m ===")

        ext = 'lerc' if args.format == 'lerc' else 'png'
        hm_path = out_dir / f"{slug}_heightmap.{ext}"
        bare_path = out_dir / f"{slug}_bare.{ext}"
        cad_path = out_dir / f"{slug}_cadastre.png"

        # Fetch order: bare first (despike reference), then SM5. SM5 spikes
        # of 50-400 m would otherwise dominate the heightfield — ČÚZK source
        # data has known LIDAR backscatter glitches that gen_detail.py's
        # mesh pipeline filters out before meshing. Heightfield must do the
        # same or buildings/cliffs disappear under sky-poking artefacts.
        if bare_path.exists() and not args.refresh_bare:
            print(f"  reusing cached bare from {bare_path.name}")
            bare_data = decode_bare_from_disk(bare_path)
        else:
            print(f"  fetching DMR5G bare earth …")
            bare_data = fetch_bare_grid(args.cx, args.cy, half, step)

        sm5_data = _fetch_sm5_grid(args.cx, args.cy, half, step)
        if sm5_data.shape != bare_data.shape:
            # Theoretically same step → same shape, but SM5 merge() with
            # bounds can pad by 1 cell. Resize bare to match SM5 grid.
            bare_data = np.array(
                Image.fromarray(bare_data).resize(
                    (sm5_data.shape[1], sm5_data.shape[0]), Image.BILINEAR),
                dtype=np.float64,
            )
        sm5_data = despike_sm5(sm5_data, bare_data, dmr_ceiling=50.0)

        # Shared y-range covers both SM5 (with buildings/trees) and bare.
        # Single uniform pair lets the viewer swap samplers without re-deriving
        # vertex range. Bare's min/max usually lies entirely inside SM5's range.
        y_min = float(min(sm5_data.min(), bare_data.min()))
        y_max = float(max(sm5_data.max(), bare_data.max()))

        _encode_heightmap_file(sm5_data, y_min, y_max, hm_path, ring_mze)
        print(f"  heightmap:    {hm_path.stat().st_size/1024:>7.1f} KB, "
              f"{sm5_data.shape[0]}×{sm5_data.shape[1]} px, "
              f"Y {y_min:.1f}–{y_max:.1f} m")
        _encode_heightmap_file(bare_data, y_min, y_max, bare_path, ring_mze)
        print(f"  bare:         {bare_path.stat().st_size/1024:>7.1f} KB")
        n = sm5_data.shape[0]

        # Emit one ortho per requested quality tier as JPEG + KTX2 (ETC1S).
        # Naming: `<slug>_ortho_<tier>.jpg` (basisu source + fallback) and
        # `<slug>_ortho_<tier>.ktx2` (what the viewer loads for tiers ≥ 2048).
        # WebP was dropped — the viewer never loaded it (KTX2 wins) and its
        # method=6 encode dominated gen time.
        # Make sure every SM5 sheet covering this ring is cached BEFORE
        # the first composite build. Without this, gaps in cache show
        # up as empty stripes in the ortho — exactly the recurring
        # "one stripe didn't load" complaint. Per-ring call because each
        # ring has its own bbox extent.
        ensure_sm5_cached(args.cx, args.cy, half,
                          fetch_missing=not args.no_fetch_missing)
        ortho_files = {}
        for tier in tiers:
            t = ORTHO_TIERS[tier]
            tier_size = max(64, int(round(size * t["scale"])))
            composite = build_ortho_composite(args.cx, args.cy, half, tier_size)
            jpg_path = out_dir / f"{slug}_ortho_{tier}.jpg"
            save_ortho_jpeg(composite, jpg_path, t["quality"], t["subsampling"])
            jpg_kb = round(jpg_path.stat().st_size / 1024, 1)
            # KTX2 (ETC1S) — only worth it for tiers ≥ 2048 px; smaller
            # tiers are already tiny on GPU (low @ 1024² = 4 MB raw RGB,
            # already not a concern) and the ~5 s basisu pass would
            # dominate gen time per ring.
            ktx2_name = None
            ktx2_kb = None
            if tier_size >= 2048:
                ktx2_path = out_dir / f"{slug}_ortho_{tier}.ktx2"
                try:
                    encode_ortho_ktx2(jpg_path, ktx2_path)
                    ktx2_name = ktx2_path.name
                    ktx2_kb = round(ktx2_path.stat().st_size / 1024, 1)
                except FileNotFoundError:
                    print(f"  (ktx2 {tier} skipped: basisu not installed)")
                except subprocess.CalledProcessError as e:
                    err = (e.stderr or "").strip()[:200] or repr(e)
                    print(f"  (ktx2 {tier} skipped: rc={e.returncode}, stderr={err})")
            tier_entry = {
                "file": jpg_path.name,
                "size_px": tier_size,
                "kb": jpg_kb,
            }
            if ktx2_name:
                tier_entry["ktx2_file"] = ktx2_name
                tier_entry["ktx2_kb"] = ktx2_kb
            ortho_files[tier] = tier_entry
            extra = f"  ktx2 {ktx2_kb:>6.1f} KB" if ktx2_name else ""
            print(f"  ortho_{tier}: {tier_size}×{tier_size}  "
                  f"jpg {jpg_kb:>7.1f} KB (q={t['quality']}, "
                  f"sub={'4:2:0' if t['subsampling']==2 else '4:4:4'}, prog){extra}")
        # No more legacy `<slug>_ortho.jpg` copy — the v1/v2 viewers that
        # needed it were retired (June 2026) and the duplicate cost ~35 MB
        # per ring. The manifest's `ortho_file` field now points straight at
        # the default tier's JPEG. Drop a stale copy left by older gens
        # (regenerable build artifact, hard delete is fine).
        stale_legacy = out_dir / f"{slug}_ortho.jpg"
        if stale_legacy.exists():
            stale_legacy.unlink()
            print(f"  removed stale legacy {stale_legacy.name}")

        cad_ok = False
        cad_ktx2_path = out_dir / f"{slug}_cadastre.ktx2"
        cad_ktx2_ok = False
        parcels_path = out_dir / f"{slug}_parcels.json"
        buildings_path = out_dir / f"{slug}_buildings.json"
        vec_counts = None
        if not args.no_cadastre:
            print(f"  fetching cadastre via {INZERATOR_PROXY} …")
            cad_ok = fetch_cadastre(args.cx, args.cy, half,
                                     args.cadastre_size, cad_path)
            if cad_ok:
                print(f"  cadastre.png:  {cad_path.stat().st_size/1024:.1f} KB, "
                      f"{args.cadastre_size}×{args.cadastre_size}")
                # KTX2 compressed mirror of the cadastre — viewer prefers it
                # over the PNG (8× GPU saving via ETC1S transcoding).
                try:
                    encode_cadastre_ktx2(cad_path, cad_ktx2_path)
                    cad_ktx2_ok = True
                    print(f"  cadastre.ktx2: {cad_ktx2_path.stat().st_size/1024:.1f} KB, 4096×4096 ETC1S")
                except FileNotFoundError:
                    print(f"  (cadastre KTX2 skipped: basisu not installed)")
                except subprocess.CalledProcessError as e:
                    err = (e.stderr or "").strip()[:200] or repr(e)
                    print(f"  (cadastre KTX2 skipped: rc={e.returncode}, stderr={err})")
            # Vector cadastre (parcels + buildings) — same data source as the
            # raster path, but lets the viewer skip the 64 MB R8 upload.
            # Generated alongside the PNG so existing slugs keep the raster
            # fallback if the viewer is older.
            vec_counts = fetch_vector_cadastre(args.cx, args.cy, half,
                                                parcels_path, buildings_path)
            if vec_counts:
                pkb = round(parcels_path.stat().st_size / 1024, 1)
                bkb = round(buildings_path.stat().st_size / 1024, 1)
                print(f"  parcels.json: {pkb:>6.1f} KB ({vec_counts['parcels']} parcel(s))")
                print(f"  buildings:    {bkb:>6.1f} KB ({vec_counts['buildings']} building(s))")

        ring_meta = {
            "slug": slug,
            "half": half,
            "step": step,
            "side_m": 2 * half,
            "heightmap_size": n,
            "ortho_size": size,
            "y_min": y_min,
            "y_max": y_max,
            "heightmap_file": hm_path.name,
            "heightmap_format": args.format,
            "bare_file": bare_path.name,
            # legacy field — now an alias for the default tier JPEG (no copy)
            "ortho_file": ortho_files[args.ortho_default]["file"],
            "ortho_default": args.ortho_default,    # name of the default tier
            "ortho_tiers": ortho_files,             # full tier table
        }
        if args.format == 'lerc':
            ring_meta["max_z_error"] = ring_mze
        if cad_ok:
            ring_meta["cadastre_file"] = cad_path.name
            ring_meta["cadastre_size"] = args.cadastre_size
        if cad_ktx2_ok:
            ring_meta["cadastre_ktx2_file"] = cad_ktx2_path.name
        if vec_counts:
            ring_meta["parcels_file"] = parcels_path.name
            ring_meta["buildings_file"] = buildings_path.name
            ring_meta["parcel_count"] = vec_counts["parcels"]
            ring_meta["building_count"] = vec_counts["buildings"]
        manifest["rings"].append(ring_meta)
        total_bytes += (hm_path.stat().st_size
                        + bare_path.stat().st_size
                        + (out_dir / ortho_files[args.ortho_default]["file"]).stat().st_size
                        + (cad_path.stat().st_size if cad_ok else 0))

    # Overall Y range across all rings (used by viewer for camera framing
    # and shared Y normalisation).
    all_y_min = min(r["y_min"] for r in manifest["rings"])
    all_y_max = max(r["y_max"] for r in manifest["rings"])
    manifest["y_min"] = all_y_min
    manifest["y_max"] = all_y_max

    write_json_atomic(out_dir / "manifest.json", manifest)
    print(f"\n=== Total: {total_bytes/1048576:.2f} MB across {len(rings)} rings ===")
    print(f"  Y range overall: {all_y_min:.1f}–{all_y_max:.1f} m")


if __name__ == "__main__":
    main()
